site_url: https://egizianoeg.github.io/String-Plus/
site_name: StringPlus
site_author: "@EgizianEG"
site_description: The Documentation Site for The StringPlus Luau Library

repo_name: EgizianEG/String-Plus
repo_url: https://github.com/EgizianoEG/String-Plus

docs_dir: Docs
site_dir: Site
remote_branch: gh-pages
use_directory_urls: true

theme:
    name: material
    language: en
    custom_dir: Docs/Overrides
    favicon: Images/SiteIcon.png
    icon:
        repo: fontawesome/brands/github
        logo: material/code-string

    font:
        text: Roboto
        code: Fira Mono

    features:
        - header.autohide
        - navigation.top
        - navigation.tabs
        - navigation.footer
        - navigation.tracking
        - navigation.indexes
        # - navigation.instant

        # - toc.follow
        # - toc.integrate

        - search.share
        - search.suggest
        - search.highlight

        - content.action.view
        - content.action.edit
        - content.code.copy
        - content.tooltips
    
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
            icon: material/brightness-7
            name: Light Mode
        primary: teal
        accent: light blue
    
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Dark Mode
        primary: blue grey
        accent: light blue

plugins:
    - tags
    - macros:
        module_name: Docs/Extra/Macros
        include_dir: Docs/Extra
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - social:
        cards: true
        cards_font: Roboto
        cards_color:
          fill: "#008C7D"
          text: "#F7F8F9"
    - minify:
       minify_html: true

markdown_extensions:
    - toc:
        title: On This Page
        toc_depth: 3
        permalink: ⚓︎
        permalink_title: Anchor Link
    - markdown.extensions.abbr
    - tables
    - abbr
    - attr_list
    - admonition
    - footnotes
    - def_list
    - md_in_html
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - Docs/Overrides/.icons
    - pymdownx.tabbed:
        alternate_style: true

extra:
  generator: true
  # social:
  #   - icon: custom/robloxstudio
  #     link: https://devforum.roblox.com/t/2094017
  #     name: DevForum Topic
  #   - icon: simple/roblox
  #     link: https://www.roblox.com/library/11868937809
  #     name: Roblox Model

extra_css:
  - Stylesheets/LightMode.css
  - Stylesheets/DarkMode.css
  - Stylesheets/Extra.css
  - Stylesheets/Icons.css

extra_javascript:
  - Extra/Java.js

# Documentation Tree:
nav:
  - Home: index.md
  - Main Module: Modules/MainModule.md
  - Sub-Modules:
      - Validator: Modules/Validator.md
      - Random: Modules/Random.md
      - Iterators: Modules/Iterators.md
      - Stringify: Modules/Stringify.md
      - UTF8Reverse: Modules/UTF8Reverse.md
  - Change Log: ChangeLog.md