site_url: https://egizianoeg.github.io/String-Plus/
site_name: StringPlus
site_author: "@EgizianEG"
site_description: The Documentation Site for The StringPlus Luau Library

repo_name: EgizianEG/String-Plus
repo_url: https://github.com/EgizianoEG/String-Plus

docs_dir: Docs
site_dir: Site
remote_branch: gh-pages
use_directory_urls: true

theme:
    language: en
    name: material
    custom_dir: Docs/Overrides
    favicon: Images/SiteIcon.png
    icon:
        repo: fontawesome/brands/github
        logo: material/code-string

    font:
        text: Roboto
        code: Fira Mono

    features:
        - header.autohide
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.footer

        - search.share
        - search.suggest
        - search.highlight

        - content.action.view
        - content.action.edit
        - content.code.copy
        - content.tooltips
    
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
            icon: material/brightness-7
            name: Light Mode
        primary: teal
        accent: light blue
    
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Dark Mode
        primary: blue grey
        accent: light blue

plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - tags
    - social:
        cards: true
        cards_font: Roboto
        cards_color:
          fill: "#008C7D"
          text: "#F7F8F9"
    - minify:
       minify_html: true

markdown_extensions:
    - toc:
        permalink: ⚓︎
        permalink_title: Anchor Link
        
    - abbr
    - admonition
    - footnotes
    - def_list
    - pymdownx.emoji
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

extra:
  generator: true
  social:
    - icon: Custom/RobloxStudioIcon
      link: https://devforum.roblox.com/t/2094017
      name: DevForum Topic
    - icon: simple/roblox
      link: https://www.roblox.com/library/11868937809
      name: Roblox Model

extra_css:
  - Stylesheets/LightMode.css
  - Stylesheets/DarkMode.css

# Documentation Tree:
nav:
  - Home: index.md
  - Main Module: MainModule.md
  - Sub-Modules:
      - Validator: "SubModules/Validator.md"
      - Random: "SubModules/Random.md"
      - Iterators: "SubModules/Iterators.md"
      - Stringify: "SubModules/Stringify.md"
      - UTF8Reverse: "SubModules/UTF8Reverse.md"